@echo off
echo Starting backend server...
start cmd /k "cd backend && npm install && npm start"
timeout /t 3
echo Starting React app...
start cmd /k "npm install && npm start"
echo Both servers are starting...